# -*- coding: utf-8 -*-
"""Week 2 Assignment 01 solution

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vP9QpcJuXSyk8nESocnQRws04jBe0daY

**Week 2 Assignment 01**
"""

# Solution 01
print("Hurry Up!!")

# Solution 02
a="Hi"
b="Arjuna"
c="Bhimaa"
print("Hi",a, b, c)

# solution 3
# prompt: extension of python files sabed

# Save Python files with a specific extension
def save_python_files(file_names, extension):
  for file_name in file_names:
    with open(file_name + extension, "w") as f:
      f.write("Code goes here...")

# Example usage:
file_names = ["file1", "file2", "file3"]
extension = ".py"
save_python_files(file_names, extension)

# solution 4
a=input("Enter the value")

# solution 5
d=-20
if (d>0)
  print(d)
if (d<0):
  print(-1*d)

# solution 6
for i in range(5):
  print(i)

# solution 7
for i in range(10):
  print("2*",(i),"=",2*(i+1))

# solution 8
a=1
for i in range(5):
  a=a*(i+1)
print(a)

# solution 9
d=5
while (d>1):
  d=d-1
  print(d)

# solution 10
d="a"
for i in range(2):
  d=d+1
  print(d)